### PR TITLE
Design-teardown project

### PR DESCRIPTION
**Pull request by nriqu322**
This is a HEAT MAP of the Smashing Magazine Homepage
We used Grid, flexbox and float to layout sections.
Added a Scale of gray to highlight different elements.

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: great!
Here are changes you need to implement, before this project can be approved:

* [x] Navbar should use `div` and positions elements as at the source page (content is not important) ([link to page](https://www.smashingmagazine.com/)) Take a look carefully, five navbar buttons are inside separate `div`, logo and search button are outside.
* [x] `article-container-e`, `article-container-h`, `container-i` ,  `article-container-f`, all `inner-article-comments` should be articles not div's
* [x] Files not related to the project should not be committed and added to .gitignore (e.g. `.DS_Store`) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by nriqu322** [comment]
All the requested changes were made.

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for full feedback! :smile: 

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by nikasulo** [comment]
# This is really awesome @nriqu322 and @Elbie-em!
Looks really neat and I must say, you put in a lot of work! However, you seem to have overlooked some very important comments @pelzolga123 made :frowning: and as such, I have gone on to attach them below. Please take a look and consider them strongly as they're hard requirements :100: 

> ## Hi Team! 
> ### Your project looks  great!
> Here are changes you need to implement, before this project can be approved:
> 
> * [x]  Navbar should use `div` and positions elements as at the source page (content is not important) ([link to page](https://www.smashingmagazine.com/)) Take a look carefully, five navbar buttons are inside separate `div`, logo and search button are outside.
> * [x]  `article-container-e`, `article-container-h`, `container-i` ,  `article-container-f`, all `inner-article-comments` should be articles not div's
> * [x]  Files not related to the project should not be committed and added to .gitignore (e.g. `.DS_Store`) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
> 
> ### Please kindly fix the above issues and send another code review request.
> If you have any questions or need help, you can message me on slack (@ Olga Pelts). _Happy coding_

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by nriqu322** [comment]
Hi Tolulope Olusakin, actually we made those changes but forgot to update the live demo link.

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi Team, you have done a great job. 🙂  Congratulations on implementing some of the changes requested by previous reviewers. Find comment below:
- Let us fix the overlapping text in the nav
overlap
- Let us fix the comment by @pelzolga123 which says use ```<article>``` instead of ```<div>```.
Like this
art
 
Kindly make these changes and submit another code review 👍 
Happy coding 💻

**Comment by addod19** [comment]
Hi Kindly ignore the second comment

**Comment by nriqu322** [comment]
Nav overlap fixed.

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes 🔴

Hi Team, you did a great job removing the overlapping text but it also created a bug. This is how the nav looks like now. 💯 
red
 To fix this try decreasing the ```padding-left``` and ```padding-right``` in the ``` .nav-links``` to about  ```15px``` and ```25px``` respectively. Or we can play around with the ```px``` 🙂 

Good luck in fixing it. 🙌 
Happy coding 💻

**Comment by Anna-Myzukina** [comment]
### Pull Request under the review by Anna Muzykina (TSE)

**Comment by Anna-Myzukina** [comment]
## Hi team!
### Nice job! Project looks! :+1: 

## Status [Approved]

Thank you for doing all the changes you are a true MVP! :1st_place_medal: 



#### Go ahead and merge to master.
#### Goodluck in your next project Happy coding

**Review by Anna-Myzukina — APPROVED** [review]

**Pull request merged**
